delete from events where price != 0;
INSERT INTO events (name, description, price, totalTickets, location, eventDate, userId)
VALUES ('Taylor Swift The Eras Tour', 'Experience Taylor Swifts record-breaking Eras Tour live!',
        499.99, 100, 'MetLife Stadium, New Jersey',
        to_timestamp((EXTRACT(EPOCH FROM NOW()) + (FLOOR(RANDOM() * 14) - 7) * 86400)),
        'user_2bFMHkGxZPWVVyJ5QEJQxfsCkxB'),
       ('NBA Finals 2024 - Game 1', 'Witness the opening game of the NBA Finals!', 899.99, 50,
        'Madison Square Garden, New York',
        to_timestamp((EXTRACT(EPOCH FROM NOW()) + (FLOOR(RANDOM() * 14) - 7) * 86400)),
        'user_2bFMHkGxZPWVVyJ5QEJQxfsCkxB'),
       ('Hamilton - Broadway', 'Dont miss the award-winning musical phenomenon!', 299.99, 75,
        'Richard Rodgers Theatre, New York',
        to_timestamp((EXTRACT(EPOCH FROM NOW()) + (FLOOR(RANDOM() * 14) - 7) * 86400)),
        'user_2dOPKmMyZRXXazL7SGLSzhsEmzD'),
       ('Coldplay World Tour', 'Join Coldplay for an unforgettable night of music!', 150.00, 200,
        'Wembley Stadium, London',
        to_timestamp((EXTRACT(EPOCH FROM NOW()) + (FLOOR(RANDOM() * 14) - 7) * 86400)),
        'user_2dOPKmMyZRXXazL7SGLSzhsEmzD'),
       ('Comic Con 2024', 'The ultimate pop culture convention!', 85.00, 1000,
        'Javits Center, New York',
        to_timestamp((EXTRACT(EPOCH FROM NOW()) + (FLOOR(RANDOM() * 14) - 7) * 86400)),
        'user_2dOPKmMyZRXXazL7SGLSzhsEmzD'),
       ('Ed Sheeran Mathematics Tour',
        'An intimate evening with Ed Sheeran performing his greatest hits', 125.00, 150,
        'O2 Arena, London',
        to_timestamp((EXTRACT(EPOCH FROM NOW()) + (FLOOR(RANDOM() * 14) - 7) * 86400)),
        'user_2eRTLnPxYQWWbzM8THMTaisFnzE'),
       ('Premier League: Arsenal vs Manchester United',
        'A classic Premier League rivalry match at the Emirates', 199.99, 60,
        'Emirates Stadium, London',
        to_timestamp((EXTRACT(EPOCH FROM NOW()) + (FLOOR(RANDOM() * 14) - 7) * 86400)),
        'user_2fQUMpNzXSVVczN9UINUbjsGozF'),
       ('Adele: Weekend with Adele', 'Adeles spectacular Las Vegas residency show', 450.00, 80,
        'Caesars Palace, Las Vegas',
        to_timestamp((EXTRACT(EPOCH FROM NOW()) + (FLOOR(RANDOM() * 14) - 7) * 86400)),
        'user_2gPVNqOyYTWWdzO0VJOVcktHpzG'),
       ('Wimbledon 2024 - Mens Final',
        'The culmination of the worlds most prestigious tennis tournament', 750.00, 40,
        'Centre Court, All England Club, London',
        to_timestamp((EXTRACT(EPOCH FROM NOW()) + (FLOOR(RANDOM() * 14) - 7) * 86400)),
        'user_2hQWOrPzZUXXezP1WKPWdluIqzH'),
       ('Harry Potter and the Cursed Child',
        'The eighth story in the Harry Potter series comes to life on stage', 175.00, 100,
        'Palace Theatre, London',
        to_timestamp((EXTRACT(EPOCH FROM NOW()) + (FLOOR(RANDOM() * 14) - 7) * 86400)),
        'user_2iRXPsQAaVYYfAQ2XLQXemvJrzI');

alter
    publication supabase_realtime add table events;
